status = ["Build", "Lint style", "Post-Build Step"]
use_squash_merge = true
timeout_sec = 28800
block_labels = ["WIP", "blocked-by-other-PR", "merge-conflict", "awaiting-CI", "bench-after-CI"]
delete_merged_branches = false
update_base_for_deletes = true
cut_body_after = "---"
max_batch_size = 16
