status = ["Build", "Lint style"]
use_squash_merge = true
timeout_sec = 28800
block_labels = ["not-ready-to-merge", "WIP", "blocked-by-other-PR", "merge-conflict", "awaiting-CI"]
delete_merged_branches = true
update_base_for_deletes = true
cut_body_after = "---"
max_batch_size = 16
