on:
  pull_request
  #schedule:
  #- cron: '0 0 1 * *'   # Runs at 00:00 on day 1 of the month
  #workflow_dispatch:

name: Blog report

jobs:

  Monthly_PRs:
    if: github.repository == 'leanprover-community/mathlib4' && github.event.pull_request.draft == false
    name: Blog draft
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BRANCH_NAME: ${{ github.head_ref }}

    steps:
      - name: cleanup
        run: |
          find . -name . -o -prune -exec rm -rf -- {} +

      - uses: actions/checkout@v4
        with:
          repository: leanprover-community/mathlib4
          fetch-depth: 0
          ref: master

      - name: blog report
        run: |
          # The job runs on the first of each month and will process the date for the previous month
          yr="$(date --date=yesterday '+%Y')"
          mm="$(date --date=yesterday '+%m')"
          yrMth="${yr}-${mm}"  # format: 2024-07
          mth="$(date -d "${yrMth}-01" '+%B')"
          tmp_file="${yrMth}_in_mathlib.md"
          printf $'Date: %s, month: %s\ntemp file: %s\n' "${yrMth}" "${mth}" "${tmp_file}"
          PR="${{ github.event.pull_request.number }}"
          title="### ${mth} ${yr} in Mathlib summary"

          printf $'Repository: %s\nBranch: %s\n' "${{ github.repository }}" "${BRANCH_NAME}"
          git checkout origin/adomani/yd_find_label scripts/find_labels.sh
          message="$(printf '%s\n\n%s\n' "${title}" "$(./scripts/find_labels.sh "${{ github.repository }}" "${yrMth}-01" "$(date -d "$(date +%Y%m01) +1 month -1 day" +%Y-%m-%d)")")"
          echo "${message}"

          formatForGitHub () {
            echo "${1}" |
              sed '
                / [0-9]* PRs$/{
                  s=^=</details><details><summary>\n=
                  s=$=\n</summary>\n=
                }
                s=^PR \(#[0-9]* [^:]*\): .*=* \1 =' |
              sed -z '
                s=</details><details><summary>=<details><summary>=
                s=\n---\nReports\n\n=\n</details>\n\n---\n\n<details><summary>Reports</summary>\n\n=
                s=\n---[\n]*$=\n\n</details>\n&=
              '
            }

          # shellcheck disable=SC2016 # backticks should not be expanded, since they are Zulip markdown syntax
          formatForZulip () {
            echo "${1}" |
            sed '
            / [0-9]* PR[s]*$/{
              s=^=```\n\n```spoiler =
              }' |
              sed -z '
              s=\n```\n=\n=
              s=\n\n```\n=\n```\n=g
              s=\n$=\n```\n=
              '
          }

          formatForZulip "${message}" | tee "${tmp_file}"

          ./scripts/update_PR_comment.sh "${tmp_file}" "${title}" "${PR}"
