name: Test Build

on:
  push:
    branches: [ add-ghost-adj ]
  pull_request:
    branches: [ add-ghost-adj ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: leanprover/setup-lean@v1
    
    - name: Update dependencies
      run: lake update
    
    - name: Build with Lake
      run: lake build
    
    - name: Print Build Success
      run: echo 'BUILD SUCCESSFUL'
