name: Test Build

on:
  push:
    branches: [ add-ghost-adj ]
  pull_request:
    branches: [ add-ghost-adj ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | bash
        echo ~/.elan/toolchains/*/bin >> $GITHUB_PATH
        echo ~/.elan/toolchains/leanprover/bin >> $GITHUB_PATH
    
    - name: Update dependencies
      run: lake update
    
    - name: Build with Lake
      run: lake build
    
    - name: Print Build Success
      run: echo 'BUILD SUCCESSFUL'
